<template>
  <main class="poster">
    <header class="poster-header">
      <div class="logo">
        <img src="/images/stfc_logo.png" alt="STFC logo">
      </div>

      <div class="title-block">
        <h1>From Metrics to Mitigation: Visualizing and Reducing the Carbon Footprint of STFC’s Ada Cloud Computing Service</h1>
      </div>

      <div class="presenter">
        <p class="name">Ashraf Hussain</p>
        <p class="email">ashraf.hussain@stfc.ac.uk</p>
      </div>
    </header>

    <div class="top-row">
      <section class="abstract">
        <h2>Project Abstract</h2>
        <p>This project presents a suite of interactive visual tools designed to monitor, forecast, and reduce carbon intensity and energy usage. 
    The Carbon Intensity Forecast visualizes predicted carbon intensity over a 48-hour period, enabling users to schedule activities during low-impact periods, 
    with highlighted windows indicating the greenest operating times. 
    Complementing this, Usage Graphs display electricity consumption and associated carbon emissions, broken down by project, machine, experiment, 
    or user—revealing inefficiencies such as excessive idle usage in ISIS workspaces. 
    A GitHub-style heatmap offers an intuitive, color-coded overview of daily carbon footprint trends, helping users quickly assess whether their operations are becoming greener over time. 
    Additional features include workspace tracking, allowing individuals to monitor energy and carbon metrics in real time, and machine size usage tracking, providing average emission data to encourage efficient resource choices. 
    Together, these tools aim to raise awareness, promote sustainability, and support data-driven decision-making within the STFC community. </p>
      </section>
    </div>

    <article class="segment segment-electricity">
      <h2>Electricity</h2>

      <div class="col-stack">
        <section>
          <h3>How do we get this data?</h3>
          
          <div class="inline-logo">
            <img src="/images/prometheus_logo.png" alt="Prometheus" />
            <img src="/images/ada_logo.png" alt="Ada Logo" />
          </div>

          <ul>
            <li>Pull <code>node_cpu_seconds_total</code> from Ada's Prometheus Database (Both idle and busy cpu usage)</li>
            <li>Assume that a cpu core uses 12 W when busy, 1 W when idle</li>
          </ul>
        </section>

        <section class="new-section">
          <h3>What is Ada?</h3>
          <p>
            Ada, formerly known as DAaaS, enables remote data access and creation of Workspaces, providing all necessary software, data, 
            and compute resources for scientific analysis. Ada offers access to the data generated by the ISIS Neutron and Muon Source and the Central Laser Facility (CLF). 
            They also host various training courses, giving course attendees access to Workspaces for practical experience using software for analysis.
          </p>
        </section>
      </div>

      <section>
        <h3>What does this data show us?</h3>
        <img
          src="/images/estimated_usage_bar_chart.png"
          alt="Idle vs busy electricity usage chart"
          class="segment-image"
        />
        <ul>
          <li>~60% of electricity usage is idle</li>
          <li>Why?</li>
          <ul>
            <li>"Zombie" VMs: Users leaving Virtual Machines active while not using them.</li>
            <li>Overprovisioning: Users selecting the largest machine size regardless of actual need.</li>
          </ul>
        </ul>
      </section>

      <section>
        <h3>How can we use this to reduce carbon footprint?</h3>
        <p>Highlight wasteful idle usage and encourage users to shut down workspaces.</p>
        <img
          src="/images/workspace_tracker.png"
          alt="Workspace tracker UI"
          class="segment-image"
        />
        <ul>
          <li>Workspace tracker: Implementing a card that shows idle electricity usage and waste carbon emissions.</li>
          <li>Upfront Costing: Display average carbon usage values for each machine size before creation.</li>
        </ul>
      </section>
    </article>

    <article class="segment segment-intensity">
      <h2>Carbon Intensity</h2>

      <section>
        <h3>How do we get this data?</h3>
        <img
          src="/images/carbon_intensity_api_logo.png"
          alt="Carbon Intensity API"
          class="inline-logo-img"
        />
        <ul> The Carbon Intensity API (NESO) provides real-time and forecast data on GB grid carbon intensity. 
    It uses generation mix data (renewables, nuclear, fossil fuels) to allow apps to schedule electricity use during "cleaner" times.
        </ul>
      </section>

      <section>
        <h3>What does this data show us?</h3>
        <img
          src="/images/generation_mix.png"
          alt="Generation mix"
          class="segment-image"
        />
        <p>The generation mix breaks down electricity production (wind, solar, gas, etc.). 
    When renewables dominate, intensity drops; when fossil fuels dominate, it rises. This transparency helps users choose low-carbon periods.</p>
      </section>

      <section>
        <h3>How can we reduce footprint?</h3>
        <img
          src="/images/carbon_intensity_forecast.png"
          alt="Carbon intensity forecast chart"
          class="segment-image"
        />
        <p>The Forecast widget enables time-shifting. The line chart and highlighted "Best 3h window" help users schedule heavy computing or other tasks during low-carbon periods, reducing emissions without changing lifestyle.</p>
      </section>
    </article>

    <article class="segment segment-footprint">
      <h2>Carbon Footprint</h2>

      <section>
        <h3>Potential impact</h3>
        <p>The GitHub-style heatmap shows a year of activity. Each square is a day, colored from green (low carbon) to red (high carbon). 
    It visualizes trends, revealing wasteful usage periods (red) versus efficient operations (green), helping users intuitively understand the long-term impact of their computing choices.</p>
      </section>

      <section>
        <h3>Today’s usage</h3>
        <img
          src="/images/actual_github_commit_history_style_carbon_footprint_heatmap.png"
          alt="Actual carbon footprint heatmap"
          class="segment-image"
        />
        <p><i>Current state with heavy idle usage.</i></p>
      </section>

      <section>
        <h3>If we reduce idle & right-size machines</h3>
        <img
          src="/images/idealised_github_commit_history_style_carbon_footprint_heatmap.png"
          alt="Idealised carbon footprint heatmap"
          class="segment-image"
        />
        <p><i>Projected state with optimized resources.</i></p>
      </section>
    </article>
  </main>
</template>

<script setup>
// Static poster, no js needed
</script>

<style scoped>
.poster {
  /* Center the poster */
  margin: 1rem auto;
  background: white;
  box-shadow: 0 0 20px rgba(0,0,0,0.1);

  /* Responsive width */
  width: 100%;
  max-width: 1200px; /* Increased max-width to allow content to breathe on large screens */

  /* Reduced padding to maximize space */
  padding: 20px;
  display: flex;
  flex-direction: column;
  gap: 14px; /* Slightly tighter gap between rows */
  font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  color: #222;
}

/* Print: use full page */
@page {
  size: A0 portrait;
  margin: 0;
}

@media print {
  .poster {
    box-shadow: none;
    margin: 0;
    width: 100%;
    height: auto;
    padding: 20mm; 
    max-width: none;
  }
}

/* Title Row Styles */
.poster-header {
  display: grid;
  grid-template-columns: 0.8fr 4fr 1.2fr;
  align-items: center;
  gap: 20px;
  margin-bottom: 5px;
  border-bottom: 2px solid #eee;
  padding-bottom: 10px;
}

.poster-header img {
  max-width: 100%;
  height: auto;
  min-width: 120px; /* Ensure logo doesn't shrink too much */
}

.poster-header h1 {
  font-size: 36px; /* Increased from 28px */
  line-height: 1.1;
  margin: 0;
  font-weight: 800;
  color: #111;
}

.poster-header .presenter {
  text-align: right;
}

.poster-header .name {
  font-weight: 700;
  font-size: 24px; /* Increased from 18px */
  margin-bottom: 4px;
}

.poster-header .email {
  font-size: 18px; /* Increased from 14px */
  color: #444;
}

/* Top Row: Abstract */
.top-row {
  /* Changed from grid to block because there was no second column content */
  display: block; 
  width: 100%;
}

.abstract {
  border-radius: 12px;
  padding: 16px 20px;
  background: #f0f2f5;
  border-left: 8px solid #333;
}

.abstract h2 {
  margin-top: 0;
  font-size: 24px; /* Increased from 18px */
  margin-bottom: 8px;
  color: #222;
  font-weight: 700;
}

.abstract p {
  font-size: 16px; /* Increased from 11px */
  line-height: 1.4;
  margin-bottom: 0;
  text-align: justify;
}

/* Segment Container Styles */
.segment {
  border-radius: 12px;
  padding: 14px 18px; /* Tighter padding */
  color: #fff;
  
  /* Grid Layout */
  display: grid;
  grid-template-columns: 1fr 1fr 1fr; /* 3 Equal columns */
  gap: 25px; /* Increased gap slightly so text doesn't touch */
  align-items: start;
}

/* Segment Colour Coding*/
.segment-electricity { background: #2b87ff; }  /* blue */
.segment-intensity   { background: #e64141; }  /* red */
.segment-footprint   { background: #2da863; }  /* green */

/* Headings inside colored blocks */
.segment h2 {
  font-size: 32px; /* Increased from 22px */
  margin: 0 0 12px;
  font-weight: 800;
  
  /* Make the H2 span across the top of the 3 columns */
  grid-column: 1 / -1;
  border-bottom: 2px solid rgba(255,255,255,0.4);
  padding-bottom: 6px;
}

.segment h3 {
  font-size: 22px; /* Increased from 16px */
  margin: 0 0 10px;
  font-weight: 700;
  line-height: 1.2;
}

/* Text Sizing */
.segment p, .segment li {
  font-size: 15px; /* Increased from 12px */
  line-height: 1.4;
  font-weight: 400;
}

.segment ul {
  padding-left: 18px;
  margin: 0;
}

.segment li {
  margin-bottom: 6px;
}

/* --- UPDATED LOGO STYLING FOR SIDE-BY-SIDE --- */
.inline-logo {
  display: flex;       /* Use flexbox to put them side by side */
  flex-direction: row;
  align-items: center; /* Center them vertically relative to each other */
  gap: 12px;           /* Space between the two logos */
  margin-bottom: 12px;
}

.inline-logo img {
  max-width: 120px; /* Slightly reduced size to ensure two fit in the column */
  height: auto;
  display: block;
  background: white;
  padding: 8px;
  border-radius: 6px;
}
/* --------------------------------------------- */

.segment-image {
  width: 100%; 
  height: auto; 
  object-fit: contain; 
  border-radius: 8px;
  margin: 10px 0;
  background: white;
  padding: 8px;
  box-shadow: 0 4px 6px rgba(0,0,0,0.2);
}

.inline-logo-img {
  width: 100%;
  max-width: 180px; /* Increased from 120px */
  background: white;
  padding: 8px;
  border-radius: 6px;
  margin-bottom: 12px;
}

/* Specific adjustment for footprint to allow heatmaps to be wide */
.segment-footprint .segment-image {
  max-height: none; 
}

.col-stack {
  display: flex;
  flex-direction: column;
  gap: 20px; /* Space between Prometheus section and New Section */
}

.new-section {
  border-top: 1px solid rgba(255, 255, 255, 0.2);
  padding-top: 10px;
}
</style>